# Generated by Django 5.2.3 on 2025-07-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenthistory_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
    ]
