# Generated by Django 5.2.3 on 2025-07-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenthistory_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payer',
            new_name='user',
        ),
    ]
