# Generated by Django 5.2.3 on 2025-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_apartment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_business_property',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='size',
            field=models.CharField(default='Size not specified'),
        ),
    ]
