# Generated by Django 5.2.3 on 2025-08-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rentalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='image',
        ),
    ]
