# Generated by Django 5.2.3 on 2025-08-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_remove_rental_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalimage',
            name='rental',
        ),
        migrations.AddField(
            model_name='rental',
            name='images',
            field=models.ManyToManyField(to='rentals.rentalimage'),
        ),
    ]
