# Generated by Django 5.2.3 on 2025-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_remove_rentalimage_rental_rental_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cover',
            field=models.ImageField(default='rentals/hall-1', upload_to=''),
        ),
    ]
