# Generated by Django 5.2.3 on 2025-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rental_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='cover',
            field=models.ImageField(default='rentals/hall-1.jpeg', upload_to=''),
        ),
    ]
