# Generated by Django 5.2.3 on 2025-08-08 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rental_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalimage',
            options={'ordering': ['-rental']},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='images',
        ),
        migrations.AddField(
            model_name='rentalimage',
            name='rental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.rental'),
        ),
    ]
