# Generated by Django 5.2.3 on 2025-08-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_alter_rentalimage_options_remove_rental_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_student_dorm',
            field=models.BooleanField(default=False),
        ),
    ]
