# Generated by Django 5.2.3 on 2025-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_rental_is_student_dorm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_apartment',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_business_property',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_room',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_student_dorm',
        ),
        migrations.AddField(
            model_name='rental',
            name='type_of_rental',
            field=models.CharField(default='room'),
        ),
    ]
