# Generated by Django 5.2.3 on 2025-08-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_remove_rental_is_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='beds',
            field=models.IntegerField(default=0),
        ),
    ]
