# Generated by Django 5.2.3 on 2025-09-11 03:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0015_rentaltenants_moved_in_date_rentalrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentalrating',
            unique_together={('user', 'rental')},
        ),
    ]
