# Generated by Django 5.2.3 on 2025-07-19 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile.png', upload_to='profiles')),
                ('address', models.TextField(default='South Africa')),
                ('phone_number', models.CharField(default='No number')),
                ('acc_num', models.CharField(default='NONE')),
                ('bank_code', models.CharField(default='NONE')),
                ('subaccount_code', models.CharField(default='NONE', max_length=122)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='auth_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
