# Generated by Django 5.2.3 on 2025-07-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='acc_num',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_number',
            field=models.CharField(default='NONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_code',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subaccount_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
