# Generated by Django 5.2.3 on 2025-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_profile_acc_num_profile_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subaccount_code',
            field=models.CharField(blank=True, default='NONE', max_length=100, null=True),
        ),
    ]
