# Generated by Django 5.2.3 on 2025-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subaccount_code',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
