# Generated by Django 5.2.3 on 2025-08-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rent_spendings',
            field=models.CharField(default='0'),
        ),
    ]
