# Generated by Django 5.2.3 on 2025-08-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_profile_rent_spendings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rent_spendings',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
