# Generated by Django 5.2.3 on 2025-08-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_profile_rent_spendings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rent_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_code',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rent_spendings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
