# Generated by Django 5.2.3 on 2025-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_profile_rent_earnings_profile_subscription_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='No number', max_length=50),
        ),
    ]
