# Generated by Django 5.2.3 on 2025-09-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rent_earnings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rent_spendings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subaccount_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_code',
        ),
    ]
