# Generated by Django 5.2.3 on 2025-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='South Africa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_details',
            field=models.TextField(default='South Africa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile.png', upload_to='profiles'),
        ),
    ]
