# Generated by Django 5.2.3 on 2025-07-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_address_profile_contact_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='No number'),
        ),
    ]
