# Generated by Django 5.2.3 on 2025-07-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_contact_details_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
