# Generated by Django 5.2.3 on 2025-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_profile_pic_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rentals',
            field=models.IntegerField(default=0),
        ),
    ]
