# Generated by Django 5.2.3 on 2025-07-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_rentals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rentals',
        ),
    ]
