# Generated by Django 5.2.3 on 2025-07-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_payment_delete_rentalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acc_num',
            field=models.CharField(default='NONE'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bank_code',
            field=models.CharField(default='NONE'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subaccount_code',
            field=models.CharField(default='NONE', max_length=122),
        ),
    ]
